export const ActionTypes = {
    SET_FEEDS: 'SET_FEEDS',
    SELECTED_FEEDS: 'SELECTED_FEEDS',
    REMOVE_SELECTED_FEED: 'REMOVE_SELECTED_FEED',
    SET_SUBSCRIBED_FEED:'SET_SUBSCRIBED_FEED',

    SET_USER: 'SET_USER',
    REMOVE_USER: 'REMOVE_USER',
    SET_USERTOKEN: 'SET_USERTOKEN',
    DELETE_USERTOKEN: 'DELETE_USERTOKEN',
    SET_USERID: 'SET_USERID',
    REMOVE_USERID: 'REMOVE_USERID',
    USER_FOLLOWERS:'USER_FOLLOWERS',
    USER_FOLLOWING:"USER_FOLLOWING",
    SET_THEME: 'SET_THEME',
    CHANGE_THEME: 'CHANGE_THEME',
    CURRENT_THEME:'CURRENT_THEME',
    SET_APP_CONF: 'SET_APP_CONF',
    REMOVE_APP_CONF: 'REMOVE_APP_CONF',

    SET_LOADING: 'SET_LOADING',
    STOP_LOADING: 'STOP_LOADING',

    SET_NOTIFICATIONS:'SET_NOTIFICATIONS',

    SET_EVENTDATA:'SET_EVENTDATA'
}